# -*- coding: utf-8 -*-
"""locgi_training_advanced.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/ton-drive-id
"""

# ==========================================
# 1. INSTALLATION DES DÉPENDANCES
# ==========================================

!pip install huggingface-hub safetensors datasets pandas numpy torch matplotlib tqdm

import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader
import numpy as np
import pandas as pd
import json
import os
from safetensors.torch import load_file, save_file
from huggingface_hub import hf_hub_download, upload_file
from datasets import load_dataset
from tqdm import tqdm
import matplotlib.pyplot as plt
from google.colab import files

print("✅ Dépendances installées")
print(f"PyTorch version: {torch.__version__}")
print(f"CUDA disponible: {torch.cuda.is_available()}")

# ==========================================
# 2. TÉLÉCHARGER LE MODÈLE DEPUIS HUGGING FACE
# ==========================================

# 🔑 REMPLACE PAR TON USERNAME
USERNAME = "ton-username"  # <-- METS TON USERNAME ICI
REPO_ID = f"{USERNAME}/locgi"

print(f"📦 Téléchargement du modèle depuis {REPO_ID}...")

# Télécharger les poids et le vocabulaire
try:
    poids_path = hf_hub_download(
        repo_id=REPO_ID,
        filename="gopu_poids.safetensors"
    )
    vocab_path = hf_hub_download(
        repo_id=REPO_ID,
        filename="vocab.json"
    )
    print("✅ Modèle téléchargé avec succès !")
except:
    print("⚠️ Modèle non trouvé, initialisation depuis zéro")
    poids_path = None
    vocab_path = None

# ==========================================
# 3. DÉFINITION DU MODÈLE LOCGI
# ==========================================

class GopuBrain(nn.Module):
    def __init__(self, vocab_size, embed_dim=128, hidden_dim=256, num_layers=2, dropout=0.3):
        super().__init__()
        self.embedding = nn.Embedding(vocab_size, embed_dim)
        self.lstm = nn.LSTM(embed_dim, hidden_dim, num_layers, batch_first=True, dropout=dropout)
        self.fc = nn.Linear(hidden_dim, vocab_size)
        self.dropout = nn.Dropout(dropout)

    def forward(self, x, hidden=None):
        x = self.embedding(x)
        x = self.dropout(x)
        out, hidden = self.lstm(x, hidden)
        return self.fc(out), hidden

# ==========================================
# 4. CHARGER LE VOCABULAIRE
# ==========================================

if vocab_path:
    with open(vocab_path, "r", encoding="utf-8") as f:
        char_to_int = json.load(f)
    print(f"✅ Vocabulaire chargé: {len(char_to_int)} caractères")
else:
    # Vocabulaire par défaut
    char_to_int = {
        '\n': 0, ' ': 1, "'": 2, '.': 3, ',': 4, '!': 5, '?': 6,
        'a': 7, 'b': 8, 'c': 9, 'd': 10, 'e': 11, 'f': 12, 'g': 13,
        'h': 14, 'i': 15, 'j': 16, 'k': 17, 'l': 18, 'm': 19, 'n': 20,
        'o': 21, 'p': 22, 'q': 23, 'r': 24, 's': 25, 't': 26, 'u': 27,
        'v': 28, 'w': 29, 'x': 30, 'y': 31, 'z': 32, 'é': 33, 'è': 34,
        'ê': 35, 'à': 36, 'ç': 37, 'ï': 38, 'ô': 39, 'û': 40, 'œ': 41
    }

int_to_char = {i: c for c, i in char_to_int.items()}
vocab_size = len(char_to_int)

# ==========================================
# 5. CHARGER UN DATASET DE QUALITÉ
# ==========================================

print("\n📚 Chargement des datasets...")

# Dataset 1: Wikipedia en français
try:
    print("Chargement de Wikipedia FR...")
    wiki_dataset = load_dataset("wikipedia", "20220301.fr", split="train", streaming=True)
    print("✅ Wikipedia chargé")
except:
    print("⚠️ Wikipedia non disponible, utilisation de dataset alternatif")

# Dataset 2: Datasets alternatifs
try:
    print("Chargement de datasets additionnels...")
    # OSCAR (corpus web français)
    oscar_dataset = load_dataset("oscar", "unshuffled_deduplicated_fr", split="train", streaming=True)
    print("✅ OSCAR chargé")
except:
    print("⚠️ OSCAR non disponible")

# Dataset 3: Fichiers locaux
try:
    print("Chargement des fichiers locaux...")
    with open("corpus.txt", "r", encoding="utf-8") as f:
        local_corpus = f.read()
    print(f"✅ Corpus local: {len(local_corpus)} caractères")
except:
    local_corpus = ""
    print("⚠️ Aucun corpus local trouvé")

# ==========================================
# 6. PRÉPARATION DES DONNÉES
# ==========================================

class CharDataset(Dataset):
    def __init__(self, text, seq_length=128):
        self.text = text
        self.seq_length = seq_length
        self.data = [char_to_int.get(c, 0) for c in text]

    def __len__(self):
        return max(0, len(self.data) - self.seq_length)

    def __getitem__(self, idx):
        x = torch.tensor(self.data[idx:idx+self.seq_length], dtype=torch.long)
        y = torch.tensor(self.data[idx+1:idx+self.seq_length+1], dtype=torch.long)
        return x, y

# ==========================================
# 7. INITIALISATION DU MODÈLE
# ==========================================

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"💻 Device: {device}")

# Modèle plus grand pour Colab
model = GopuBrain(vocab_size, embed_dim=128, hidden_dim=256, num_layers=2).to(device)

# Charger les poids existants si disponibles
if poids_path:
    try:
        state_dict = load_file(poids_path)
        # Ajuster si nécessaire
        model.load_state_dict(state_dict, strict=False)
        print("✅ Poids précédents chargés")
    except:
        print("⚠️ Impossible de charger les poids, initialisation aléatoire")

print(f"📊 Modèle: {sum(p.numel() for p in model.parameters()):,} paramètres")

# ==========================================
# 8. PRÉPARER LE CORPUS POUR L'ENTRAÎNEMENT
# ==========================================

def collect_corpus(max_chars=1_000_000):
    """Collecte un grand corpus à partir de différentes sources"""
    print("📚 Collecte du corpus...")
    corpus_parts = []

    # 1. Corpus local
    if local_corpus:
        corpus_parts.append(local_corpus * 10)  # Multiplier pour plus de données
        print(f"  ✅ Local: {len(local_corpus)} caractères")

    # 2. Wikipedia
    try:
        wiki_text = ""
        for i, sample in enumerate(wiki_dataset):
            if i > 100:  # Limiter pour la démo
                break
            wiki_text += sample["text"] + "\n\n"
        if wiki_text:
            corpus_parts.append(wiki_text)
            print(f"  ✅ Wikipedia: {len(wiki_text)} caractères")
    except:
        print("  ⚠️ Wikipedia ignoré")

    # 3. OSCAR
    try:
        oscar_text = ""
        for i, sample in enumerate(oscar_dataset):
            if i > 50:  # Limiter pour la démo
                break
            oscar_text += sample["text"] + "\n\n"
        if oscar_text:
            corpus_parts.append(oscar_text)
            print(f"  ✅ OSCAR: {len(oscar_text)} caractères")
    except:
        print("  ⚠️ OSCAR ignoré")

    # 4. Ajouter des phrases manuelles pour enrichir
    manual_text = """
    L'intelligence artificielle est une technologie qui transforme le monde.
    Le machine learning permet aux ordinateurs d'apprendre à partir de données.
    Les réseaux de neurones sont inspirés du cerveau humain.
    Le deep learning utilise des couches multiples pour l'apprentissage.
    Python est le langage préféré pour l'intelligence artificielle.
    PyTorch est une bibliothèque puissante pour le deep learning.
    Les données sont le carburant de l'intelligence artificielle.
    La France est un pays européen avec une riche histoire.
    Paris est la capitale de la France et une ville magnifique.
    Le football est le sport le plus populaire du monde.
    """
    corpus_parts.append(manual_text * 20)
    print(f"  ✅ Manuel: {len(manual_text)} caractères")

    # Combiner
    full_corpus = " ".join(corpus_parts)

    # Limiter pour éviter de saturer
    if len(full_corpus) > max_chars:
        full_corpus = full_corpus[:max_chars]

    print(f"📊 Corpus total: {len(full_corpus):,} caractères")
    return full_corpus

# Collecter le corpus
corpus = collect_corpus(200_000)  # 200K caractères pour commencer

# Créer le dataset
seq_length = 128
dataset = CharDataset(corpus, seq_length)
dataloader = DataLoader(dataset, batch_size=64, shuffle=True, num_workers=2)

print(f"📊 Dataset: {len(dataset)} échantillons")

# ==========================================
# 9. ENTRAÎNEMENT SUR COLAG
# ==========================================

# Hyperparamètres
learning_rate = 0.002
epochs = 50
optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)
scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(optimizer, patience=3, factor=0.5)
criterion = nn.CrossEntropyLoss()

print(f"\n🚀 Entraînement sur {device}")
print(f"📊 Paramètres:")
print(f"  - Learning rate: {learning_rate}")
print(f"  - Époques: {epochs}")
print(f"  - Sequence length: {seq_length}")
print(f"  - Batch size: 64")
print("=" * 50)

# Tracking
history = {'loss': [], 'val_loss': []}
best_loss = float('inf')

for epoch in range(epochs):
    model.train()
    total_loss = 0
    progress_bar = tqdm(dataloader, desc=f"Epoch {epoch+1}/{epochs}")

    for x, y in progress_bar:
        x, y = x.to(device), y.to(device)

        optimizer.zero_grad()
        out, _ = model(x)
        loss = criterion(out.reshape(-1, vocab_size), y.reshape(-1))
        loss.backward()

        # Gradient clipping
        torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
        optimizer.step()

        total_loss += loss.item()
        progress_bar.set_postfix({'loss': f'{loss.item():.4f}'})

    avg_loss = total_loss / len(dataloader)
    history['loss'].append(avg_loss)

    # Scheduler
    scheduler.step(avg_loss)

    # Sauvegarder le meilleur modèle
    if avg_loss < best_loss:
        best_loss = avg_loss
        save_file(model.state_dict(), "gopu_poids_best.safetensors")
        print(f"💾 Meilleur modèle sauvegardé (loss: {best_loss:.4f})")

    print(f"📊 Epoch {epoch+1}/{epochs} - Loss: {avg_loss:.4f} - LR: {optimizer.param_groups[0]['lr']:.6f}")

# ==========================================
# 10. VISUALISATION DE L'ENTRAÎNEMENT
# ==========================================

plt.figure(figsize=(10, 5))
plt.plot(history['loss'], label='Training Loss')
plt.xlabel('Époque')
plt.ylabel('Loss')
plt.title('Progression de l\'entraînement de locgi')
plt.legend()
plt.grid(True)
plt.show()

# ==========================================
# 11. SAUVEGARDE ET UPLOAD
# ==========================================

print("\n💾 Sauvegarde du modèle...")
save_file(model.state_dict(), "gopu_poids_final.safetensors")

# Sauvegarder le vocabulaire
with open("vocab.json", "w") as f:
    json.dump(char_to_int, f)

print("✅ Modèle sauvegardé localement")

# Upload vers Hugging Face
print(f"\n📤 Upload vers {REPO_ID}...")

try:
    upload_file(
        path_or_fileobj="gopu_poids_final.safetensors",
        path_in_repo="gopu_poids_final.safetensors",
        repo_id=REPO_ID,
        repo_type="model"
    )
    print("✅ Poids uploadés")

    upload_file(
        path_or_fileobj="vocab.json",
        path_in_repo="vocab.json",
        repo_id=REPO_ID,
        repo_type="model"
    )
    print("✅ Vocabulaire uploadé")
except Exception as e:
    print(f"⚠️ Erreur d'upload: {e}")
    # Télécharger localement
    files.download("gopu_poids_final.safetensors")
    files.download("vocab.json")

print(f"\n🎉 Entraînement terminé !")
print(f"👉 Modèle disponible sur: https://huggingface.co/{REPO_ID}")

# ==========================================
# 12. TEST RAPIDE
# ==========================================

def generate_text(prompt, max_len=100, temperature=0.8):
    model.eval()
    with torch.no_grad():
        data = [char_to_int.get(c, 0) for c in prompt]
        x = torch.tensor(data, dtype=torch.long).unsqueeze(0).to(device)

        result = prompt
        hidden = None

        for _ in range(max_len):
            out, hidden = model(x, hidden)
            logits = out[0, -1] / temperature
            probs = torch.softmax(logits, dim=-1)
            idx = torch.multinomial(probs, 1).item()
            char = int_to_char.get(idx, '')
            result += char
            x = torch.tensor([[idx]], dtype=torch.long).to(device)

    return result

print("\n🧪 Test de génération:")
prompts = ["Bonjour", "Le football", "L'intelligence artificielle"]

for prompt in prompts:
    generated = generate_text(prompt, 50, temperature=0.7)
    print(f"\n[Toi] > {prompt}")
    print(f"[Locgi] > {generated}")

print("\n✨ Félicitations ! locgi est maintenant un meilleur modèle !")
